services:
    cimus.gearman.client:
        class: GearmanClient
        calls:
            - [ addServers, [%cimus.gearman.servers%] ]
            
    cimus.gearman.worker:
        class: GearmanWorker
        calls:
            - [ addServers, [%cimus.gearman.servers%] ]
        scope: prototype
        
    cimus.gearman:
        class: Cimus\GearmanBundle\Services\GearmanClient
        arguments: [@cimus.gearman.client]